# Generated by Django 4.2.10 on 2024-02-08 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Org', '0002_alter_users_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
