# Generated by Django 4.2.10 on 2024-02-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Org', '0003_remove_users_username_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
