# Generated by Django 4.2.10 on 2024-02-13 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Org', '0008_alter_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
